apiVersion: v1
kind: ConfigMap
metadata:
  name: audit-webhook-configmap
data:
  volume_patch: '{"name":"internal-tls","secret":{"secretName":"internal-tls","defaultMode":420}}'
  container_patch: '{"name":"sidecar","image":"docker.io/youngpig/fluentd:latest","securityContext":{"runAsNonRoot":true},"resources":{"requests":{"memory":"100Mi","cpu":"100m"},"limits":{"memory":"250Mi","cpu":"250m"}},"imagePullPolicy":"IfNotPresent","args":["/bin/bash","-c","fluentd -c /fluentd/etc/fluent.conf"],"volumeMounts":[{"name":"varlog","mountPath":"/var/log"}]}'
