apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: serving-cert
spec:
  dnsNames:
  - audit-webhook-service.default.svc
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: audit-webhook-tls-secret
