apiVersion: v1
kind: Pod
metadata:
  name: fluentd-server
  labels:
    app: fluentd-server
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000321000
  containers:
  - name: sidecar
    image: youngpig/fluentd:server
    ports:
    - containerPort: 9880
    imagePullPolicy: IfNotPresent
    args:
    - /bin/sh
    - -c
    - fluentd -c /fluentd/etc/fluent.conf
    securityContext:
      runAsNonRoot: true
    resources:
      limits:
        memory: 250Mi
        cpu: 250m
      requests:
        memory: 100Mi
        cpu: 100m
    env:
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: NODENAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: PODIPADDRESS
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP